<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rt_simpleosm"
 *
 * Auto generated by Extension Builder 2019-03-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple OpenStreetMap',
    'description' => 'Insert a simple OpenStreetMap. No API key required!',
    'category' => 'plugin',
    'author' => 'Regis TEDONE',
    'author_email' => 'regis.tedone@gmail.com',
    'state' => 'stable',
    'version' => '4.1.3',
    'constraints' => [
        'depends' => [ 'typo3' => '12.4.0-12.4.99' ],
        'conflicts' => [],
        'suggests' => [
	        'tt_address' => '4.0.0-5.99.99',
        ],
    ],
];
